# The ``numpy`` Package

We have already mentioned the ``numpy`` package in one of our notebooks. It is one of the most commonly used Python packages. It includes n-dimensional arrays, matrices, it implements the basic mathematical operations over them etc.

## Creation a New ``numpy`` Array

When using the ``numpy`` package, the first step is to import is, of course. The package is usually imported under the shortened name ``np``. Arrays can then be created using function ``array``, which receives a Python list as an argument, e.g.:

In [0]:
import numpy as np

A = np.array([[1, 2.5, 3], [4, 5, 6], [7, 8, 9]])

print(A)

[[1.  2.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## Creating Special Arrays

There are several built-in function, which enable easier creation of commonly used special arrays. The shape of the array is passed in a list – ``[2, 2]`` – or as a tuple – ``(2, 2)``:

In [0]:
# Creating an all-zeros array.
A = np.zeros((3, 4))
print("A = \n{}\n".format(A))

# Creating an all-ones array.
B = np.ones((3, 4))
print("B = \n{}\n".format(B))

# Creating an array filled with a constant.
C = np.full((3, 4), 7)
print("C = \n{}\n".format(C))

# Creating a square matrix with ones at
#the diagonal and zeros elsewhere.
D = np.eye(4)
print("D = \n{}\n".format(D))

A = 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

B = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

C = 
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

D = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



Arrays can also be higher-dimensional, e.g.:

In [0]:
A = np.zeros([2, 2, 3])
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


There are also functions, which can create random arrays:

In [0]:
# A 3x3 array with random elements from interval [0, 5).
A = np.random.uniform(0, 5, (3, 3))
print(A)

[[3.32587154 2.2922609  1.08885542]
 [2.05155621 3.71746057 3.47356696]
 [1.81157135 1.5122476  3.12230748]]


## Indexing Elements of an Array

The individual elements of an array are indexed by listing their coordinates separated by commas in square brackets:

In [0]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

a = A[0, 0]
print("A[0, 0] = {}".format(a))

b = A[0, 1]
print("A[0, 1] = {}".format(b))

A = 
[[1 2 3]
 [4 5 6]]

A[0, 0] = 1
A[0, 1] = 2


A colon ``:`` can be sued to address a segment of elements along a certain dimension:

In [0]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

a = A[:2, 1]
print("A[:2, 1] = {}\n".format(a))

b = A[:, 0]
print("A[:, 0] = {}\n".format(b))

c = A[:2, :2]
print("A[:2, :2] = \n{}".format(c))

A = 
[[1 2 3]
 [4 5 6]]

A[:2, 1] = [2 5]

A[:, 0] = [1 4]

A[:2, :2] = 
[[1 2]
 [4 5]]


In a way similar to lists, ``numpy`` array also support indexing from the end on the array using negative indices.

## The Shape of an Array

Each array has a certain shape; it can be determined using attribute ``.shape``:

In [0]:
A = np.zeros([2, 2, 3])
print(A.shape)

(2, 2, 3)


The shape of an array can be modified using function ``np.reshape``:

In [0]:
A = np.zeros([2, 2, 3])
print("A.shape: {}".format(A.shape))

B = np.reshape(A, [3, 2, 2])
print("B.shape: {}".format(B.shape))

# The size in one dimension can be computed automatically,
# if we enter -1 instead of it.
C = np.reshape(A, [3, -1, 2])
print("C.shape: {}".format(C.shape))

A.shape: (2, 2, 3)
B.shape: (3, 2, 2)
C.shape: (3, 2, 2)


An array can be transposed using function ``.transpose``:

In [0]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

AT = A.transpose()
print("AT = \n{}\n".format(AT))

A = 
[[1 2 3]
 [4 5 6]]

AT = 
[[1 4]
 [2 5]
 [3 6]]



## Arithmetic Operations with Arrays

Arrays support the basic arithmetic operations, such as addition or multiplication. These all operate element-wise:

In [0]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 5, 4], [3, 2, 1]])
print("A = \n{}\n".format(A))
print("B = \n{}\n".format(B))

# Element-wise addition:
C = A + B
print("A + B = \n{}\n".format(C))

# Element-wise subtraction:
C = A - B
print("A - B = \n{}\n".format(C))

# Element-wise multiplication:
C = A * B
print("A * B = \n{}\n".format(C))

# Element-wise division:
C = A / B
print("A / B = \n{}\n".format(C))

A = 
[[1 2 3]
 [4 5 6]]

B = 
[[6 5 4]
 [3 2 1]]

A + B = 
[[7 7 7]
 [7 7 7]]

A - B = 
[[-5 -3 -1]
 [ 1  3  5]]

A * B = 
[[ 6 10 12]
 [12 10  6]]

A / B = 
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]



The ``numpy`` package also contains version of some standard mathematical function, such as ``sin``, ``cos`` or ``exp``, which can operate on arrays:

In [0]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

sinA = np.sin(A)
print("sin(A) = \n{}\n".format(sinA))

expA = np.exp(A)
print("exp(A) = \n{}\n".format(expA))

A = 
[[1 2 3]
 [4 5 6]]

sin(A) = 
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

exp(A) = 
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]



## Algebraic Operations

The standard algebraic operations are also defined for ``numpy`` arrays, such as the dot product, matrix product and more:

In [0]:
a = np.array([1, 2, 3])
print("a = {}".format(a))
b = np.array([4, 5, 6])
print("b = {}\n".format(b))

c = np.dot(a, b)
print("a.b = {}".format(c))

a = [1 2 3]
b = [4 5 6]

a.b = 32


In [0]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 5, 4], [3, 2, 1]])
print("A = \n{}\n".format(A))
print("B = \n{}\n".format(B))

C = np.matmul(A, B.transpose())
print("A x B = \n{}".format(C))

A = 
[[1 2 3]
 [4 5 6]]

B = 
[[6 5 4]
 [3 2 1]]

A x B = 
[[28 10]
 [73 28]]


## Group Comparisons and Indexing

It is possible to perform group comparisons on ``numpy`` array, such as identifying all elements of an array greater than or equal to 5. The result of such comparison is a binary array of the same shape, which specifies whether the condition held for each correspoding element or not.

In [0]:
A = np.array([[1, 5, 2], [7, 3, 4], [8, 0, 2]])
print(A >= 5)

[[False  True False]
 [ True False False]
 [ True False False]]


Similarly, it is also possible to index elements according to some such condition. One can use function ``np.where`` to accomplish this: it will select the indices of any elements for which the value is ``True`` in the binary array. The resulting indices can be used as an index to the original array. If we want to assign 111 to every element greater than or equal to 5, for an instance, we can do that as follows:

In [0]:
A = np.array([[1, 5, 2], [7, 3, 4], [8, 0, 2]])
index = np.where(A >= 5)
A[index] = 111

print(A)

[[  1 111   2]
 [111   3   4]
 [111   0   2]]
