# Balíček ``numpy``

V jednom z notebook-ov sme už spomínali balíček ``numpy``. Je to jeden z najčastejšie používaných python-ových balíčkov. Obsahuje n-rozmerné polia, matice, umožňuje s nimi robiť základné matematické operácie atď.

## Vytvorenie nového ``numpy`` poľa

Prvý krok pri používaní balíčka ``numpy`` prirodzene je importovať ho. Tento balíček sa najčastejšie importuje pod skráteným názvom ``np``. Pole potom môžeme vytvoriť pomocou funkcie ``array`` ktorej ako argument dáme prvky poľa vo forme zoznamu, napr.:

In [1]:
import numpy as np

A = np.array([[1, 2.5, 3], [4, 5, 6], [7, 8, 9]])

print(A)

[[1.  2.5 3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## Vytvorenie špeciálnych polí

Existuje zopár funkcií, ktoré uľahčujú vytvorenie často používaných špeciálnych polí. Tvar poľa zadávame ako zoznam – ``[2, 2]`` – alebo n-ticu – ``(2, 2)``:

In [2]:
# Vytvorenie poľa so samými nulami.
A = np.zeros((3, 4))
print("A = \n{}\n".format(A))

# Vytvorenie poľa so samými jednotkami.
B = np.ones((3, 4))
print("B = \n{}\n".format(B))

# Vytvorenie poľa naplneného danou konštantou.
C = np.full((3, 4), 7)
print("C = \n{}\n".format(C))

# Vytvorenie štvorcovej matice s jednotkami na diagonále (ostatné nuly).
D = np.eye(4)
print("D = \n{}\n".format(D))

A = 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

B = 
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

C = 
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

D = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



Polia môžu byť aj viacrozmerné, napr.:

In [3]:
A = np.zeros([2, 2, 3])
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


Existujú aj funkcie na generovanie náhodných polí:

In [4]:
# Pole rozmeru 3x3 s náhodnými prvkami z intervalu [0, 5).
A = np.random.uniform(0, 5, (3, 3))
print(A)

[[2.60773716 2.17706944 1.86185908]
 [4.35785891 1.8030173  3.93301678]
 [4.78466791 2.15806406 0.35353672]]


## Indexovanie prvkov

Jednotlivé prvky poľa sa indexujú tak, že sa v hranatých zátvorkách uvedú ich súradnice oddelené čiarkou:

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

a = A[0, 0]
print("A[0, 0] = {}".format(a))

b = A[0, 1]
print("A[0, 1] = {}".format(b))

A = 
[[1 2 3]
 [4 5 6]]

A[0, 0] = 1
A[0, 1] = 2


Pomocou ``:`` je možné adresovať aj určitý rozsah v danom rozmere alebo všetky prvky v danom rozmere:

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

a = A[:2, 1]
print("A[:2, 1] = {}\n".format(a))

b = A[:, 0]
print("A[:, 0] = {}\n".format(b))

c = A[:2, :2]
print("A[:2, :2] = \n{}".format(c))

A = 
[[1 2 3]
 [4 5 6]]

A[:2, 1] = [2 5]

A[:, 0] = [1 4]

A[:2, :2] = 
[[1 2]
 [4 5]]


Podobne ako pri zoznamoch, dá sa prirodzene aj pri ``numpy`` poliach použiť indexovanie prvkov od konca pomocou záporných indexov.

## Tvar poľa

Každé pole má určitý tvar; možno ho zistiť pomocou atribútu ``.shape``:

In [7]:
A = np.zeros([2, 2, 3])
print(A.shape)

(2, 2, 3)


Tvar poľa sa dá aj zmeniť – pomocou metódy ``np.reshape``:

In [8]:
A = np.zeros([2, 2, 3])
print("A.shape: {}".format(A.shape))

B = np.reshape(A, [3, 2, 2])
print("B.shape: {}".format(B.shape))

# Jeden rozmer sa dá dorátať aj automaticky ak namiesto neho zadáme -1:
C = np.reshape(A, [3, -1, 2])
print("C.shape: {}".format(C.shape))

A.shape: (2, 2, 3)
B.shape: (3, 2, 2)
C.shape: (3, 2, 2)


Transponovať (zmeniť poradie rozmerov) sa dá pole pomocou metódy ``.transpose``:

In [9]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

AT = A.transpose()
print("AT = \n{}\n".format(AT))

A = 
[[1 2 3]
 [4 5 6]]

AT = 
[[1 4]
 [2 5]
 [3 6]]



## Aritmetika s poľami

S poľami sa dajú realizovať aj aritmetické operácie – napr. sčítanie alebo násobenie polí po prvkoch:

In [10]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 5, 4], [3, 2, 1]])
print("A = \n{}\n".format(A))
print("B = \n{}\n".format(B))

# Sčítanie po prvkoch:
C = A + B
print("A + B = \n{}\n".format(C))

# Odčítanie po prvkoch:
C = A - B
print("A - B = \n{}\n".format(C))

# Násobenie po prvkoch:
C = A * B
print("A * B = \n{}\n".format(C))

# Delenie po prvkoch:
C = A / B
print("A / B = \n{}\n".format(C))

A = 
[[1 2 3]
 [4 5 6]]

B = 
[[6 5 4]
 [3 2 1]]

A + B = 
[[7 7 7]
 [7 7 7]]

A - B = 
[[-5 -3 -1]
 [ 1  3  5]]

A * B = 
[[ 6 10 12]
 [12 10  6]]

A / B = 
[[0.16666667 0.4        0.75      ]
 [1.33333333 2.5        6.        ]]



Balíček ```numpy``` obsahuje aj verzie klasických matematických funkcií ako ```sin```, ```cos``` alebo ```exp```, ktoré dokážu pracovať s poľami:

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print("A = \n{}\n".format(A))

sinA = np.sin(A)
print("sin(A) = \n{}\n".format(sinA))

expA = np.exp(A)
print("exp(A) = \n{}\n".format(expA))

A = 
[[1 2 3]
 [4 5 6]]

sin(A) = 
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

exp(A) = 
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]



## Algebraické operácie

S ```numpy``` poľami sa dajú vykonať aj klasické algebraické operácie – napr. skalárny súčin, násobenie matíc a pod.:

In [12]:
a = np.array([1, 2, 3])
print("a = {}".format(a))
b = np.array([4, 5, 6])
print("b = {}\n".format(b))

c = np.dot(a, b)
print("a.b = {}".format(c))

a = [1 2 3]
b = [4 5 6]

a.b = 32


In [13]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 5, 4], [3, 2, 1]])
print("A = \n{}\n".format(A))
print("B = \n{}\n".format(B))

C = np.matmul(A, B.transpose())
print("A x B = \n{}".format(C))

A = 
[[1 2 3]
 [4 5 6]]

B = 
[[6 5 4]
 [3 2 1]]

A x B = 
[[28 10]
 [73 28]]


## Hromadné porovnávanie a indexovanie prvkov

Pomocou ``numpy`` polí je možné realizovať aj hromadné porovnávanie prvkov – napr. identifikovať všetky prvky, ktoré sú väčšie, nanajvýš rovné 5. Výsledkom je binárne pole rovnakej veľkosti, ktoré špecifikuje či podmienka je pre daný prvok splnená alebo nie.

In [14]:
A = np.array([[1, 5, 2], [7, 3, 4], [8, 0, 2]])
print(A >= 5)

[[False  True False]
 [ True False False]
 [ True False False]]


Obdobne je možné prvky podľa určitej podmienky aj zaindexovať. Používa sa na to funkcia ``np.where``, ktorá z binárneho poľa vyberie súradnice ``True`` prvkov. Výslednými súradnicami je možné indexovať pôvobdné pole. Ak chceme napr. priradiť namiesto každého prvku väčšieho, nanajvýš rovného 5 číslo 111:

In [16]:
A = np.array([[1, 5, 2], [7, 3, 4], [8, 0, 2]])
index = np.where(A >= 5)
A[index] = 111

print(A)

[[  1 111   2]
 [111   3   4]
 [111   0   2]]
